version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ""            # root sans mot de passe
      MYSQL_DATABASE: "studentdb"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # n√©cessaire pour autoriser root vide
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: student-management:latest
    container_name: student-management
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /student

volumes:
  mysql-data:
